### ISSUE TITLE
_credential.getCredential is not a function

### ISSUE THREAD

**Issue by taosimple** [aliyun/darabonba-openapi#162]
按 #156 测试了 `@alicloud/credentials` 2.3.1, 2.3.0 都报错
```
 TypeError: this._credential.getCredential is not a function
    at Client.doRequest (/Users/taotao/Documents/workspace/ark-server/server/node_modules/@alicloud/openapi-client/src/client.ts:1105:56)
    at Client.callApi (/Users/taotao/Documents/workspace/ark-server/server/node_modules/@alicloud/openapi-client/src/client.ts:1382:25)
    at Client.singleSendMailWithOptions (/Users/taotao/Documents/workspace/ark-server/server/node_modules/@alicloud/dm20151123/src/client.ts:8762:57)
    at Function.sendByAliSdk (/Users/taotao/Documents/workspace/ark-server/server/src/common/mail.sender.ts:85:32)
    at TemplateController.findAll (/Users/taotao/Documents/workspace/ark-server/server/src/modules/template/template.controller.ts:67:22)
    at /Users/taotao/Documents/workspace/ark-server/server/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```

**Comment by JacksonTian** [comment]
这是因为初始化没有传入 AccessKeyID 和 AccessKeySecret
